# tasks/main.yml
---
- name: Debug OS family
  debug:
    msg: "OS Family is {{ ansible_os_family }}"

- name: Ensure Python is installed
  raw: test -e /usr/bin/python || (yum -y update && yum install -y python)
  changed_when: false
  ignore_errors: true

- name: Check if apt-get exists
  stat:
    path: /usr/bin/apt-get
  register: apt_get_check

- name: Check if yum exists
  stat:
    path: /usr/bin/yum
  register: yum_check

- name: Display package manager information
  debug:
    msg: "apt-get exists: {{ apt_get_check.stat.exists }}, yum exists: {{ yum_check.stat.exists }}"

- name: Install Apache on RedHat-based systems
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and enable Apache service on RedHat-based systems
  systemd:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Create index.html for all VMs
  template:
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
    mode: '0444'
  notify: Reload Apache  # Notify the handler to reload Apache

- name: Ensure Apache starts on boot
  systemd:
    name: httpd
    enabled: yes
    state: started
  when: ansible_os_family == "RedHat"
